import {MultiSelect} from '@mantine/core';
import '@mantine/core/styles/CloseButton.css';
import '@mantine/core/styles/Input.css';
import '@mantine/core/styles/Pill.css';
import '@mantine/core/styles/UnstyledButton.css';
import '@mantine/core/styles/PillsInput.css';
import '@mantine/core/styles/ScrollArea.css';
import '@mantine/core/styles/Button.css';
import '@mantine/core/styles/Loader.css';
import '@mantine/core/styles/Group.css';
export {MultiSelect};
