import {Drawer} from '@mantine/core';
import '@mantine/core/styles/Drawer.css';
import '@mantine/core/styles/Button.css';
import '@mantine/core/styles/Loader.css';
import '@mantine/core/styles/UnstyledButton.css';
import '@mantine/core/styles/ScrollArea.css';
import '@mantine/core/styles/Tabs.css';
import '@mantine/core/styles/ModalBase.css';
import '@mantine/core/styles/CloseButton.css';
import '@mantine/core/styles/VisuallyHidden.css';
import '@mantine/core/styles/ActionIcon.css';
import '@mantine/core/styles/Paper.css';
import '@mantine/core/styles/Overlay.css';
export {Drawer};
